site:
  title: Minato Lab
  start_page: minato-lab::home.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: ./ui/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
antora:
  extensions:
  - require: '@antora/lunr-extension'