include::partial$template.adoc[]

= AntoraページにSearchを追加

https://gitlab.com/antora/antora-lunr-extension

partials 使い方
dhirekutorimeiha partials
include は partial


Antora Default UI 使い方

Gulp CLI

You’ll need the Gulp command-line interface (CLI) to run the build.
The Gulp CLI package provides the gulp command which, in turn, executes the version of Gulp declared by the project.


You can install the Gulp CLI globally (which resolves to a location in your user directory if you’re using nvm) using the following command:



$ npm install -g gulp-cli



Verify the Gulp CLI is installed and on your PATH by running:



$ gulp --version


使い方

$ npm install (antora-ui-defaultディレクトリで)

毎回
$ gulp bundle 
gulp bundle:packでは失敗するので注意。



favicon を追加する。

https://docs.antora.org/antora-ui-default/add-static-files/

src/static フォルダを追加
favicon.icoを追加

header を編集

gulp bundle
実行してbuildする。

playbookを変更
uiのURLをローカルのパスに変更。snapshotは消す。





== フォントの変更
/home/shota/HOME/00_MyHP/minato-lab/ui/antora-ui-default/src/css/vars.css