:!sectnums:

= HOME

== はじめに

カリフォルニア在住エンジニアの日記兼、開発備忘録です。

以下の内容の記事を不定期で更新していきます。

* Asciidoc, Antora
* System Verilog
* Verilator
* Linuc

== 日記

=== 2025-01-16

本日は、Verilatorを使ってVCDファイルをダンプする方法を確認しました。VCDファイルは、シミュレーションの波形を記録したファイルです。これを使って、シミュレーションの結果を確認できます。

こちらのページを参考にしました。https://jp-seemore.com/iot/12095/

Verilator 5.0以降はタイミングのシミュレーションができるようになったため、テストベンチをSystem Verilogのみで完結させることができます。これはかなり便利です。詳細については、後日記事にまとめたいと思います。

また、Verilator インストール方法を修正しました。以下のリンクからアクセスできます。

xref:Verilator/01_install_verilator.adoc[]

使用するOSをUbuntu24.04に変更しました。タイミングシミュレーションを行うためにCpp20が必要だからです。C++20自体は、古いOSでも利用できますが、他に必要なライブラリもあるため、特に理由がなければ、最新のUbuntuを使用することをお勧めします。

=== 2025-01-15

本日はホームページの見た目を更新しました。タイトルの字の大きさを、画面サイズから自動調整するようにしました。これにより、スマートフォンからも見やすくなりました。

以下のページを参考にさせていただきました。今の時代、こういった情報にすぐアクセスできるのはありがたいですね。このホームページでもこのような情報を提供できるようにしたいです。

.【CSS】レスポンシブなfont-size指定テクニック4選
https://qiita.com/suzoo/items/8f47eaf41c09ed94e712

=== 2025-01-14

日記をつけはじました。目標は1週間に1記事投稿です。 

本日はVerilatorのインストール方法を記事にしました。VerilatorはオープンソースのEDAツールです。世の中にあるほとんどのEDAツールは有料で高価ですが、Verilatorは無料です。個人開発者としてはとてもありがたいですね。ただし、GUIがないため、コマンドラインでの操作が必要です。

記事は、以下のリンクからアクセスできます。

xref:Verilator/01_install_verilator.adoc[]

ほとんどが公式ページの引用です。特に問題なく進められるはずです。

次は、System Verilog で書いたテストベンチをコンパイルして、DUTのシミュレーションを行う方法をまとめたいと思います。